kumuluzee:
  name: categories
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8087
  datasources:
    - jndi-name: jdbc/CategoriesDS
      connection-url: jdbc:postgresql://192.168.99.100:5433/categorie
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/CategoriesDS
  rest-properties:
  healthy: true

