apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: categories-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: categorie
    spec:
      containers:
      - image: ejmric/categories:first
        name: categories
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-categories:5432/categorie
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.20.118:30188
        ports:
        - containerPort: 8087
          name: server
          protocol: TCP
